travis:
  secure:
    BINSTAR_TOKEN: DnCca+IUvMi40ampY+P/aJnFTUTSiAkm7iImTm00bDbheBiLUJkFbbzVUn7fQZLxKR5fmwUlUreIywUxvAfvwhfBjYnZ+xmczwe7E4kL67IHIjSd/JEM2hmOlvoTH7cc8EN2EZwawjK57hZhCkdAkfJDs2Upq1pE1Dps1tREb+jFnDbmXnSK84y97Jtbzw2gpLS113i670vYEc8kaTnzEvcbYFr3yMcChavhOJoArLG+IM+NbRtGhtldQXimw/MBX3uGOTXUF87dGFOPR2RW6fqZBTwgzvbhj902XtUkWiUQylz3A3h4IdJFnwtG8RsmAblzNhDVBvxvNit1OQp3/XceJkChxWs8E0RfN5RKE/7pCiCGsDKo0FttI4SKbIF5/eeMlh0l3p9bx+Iumz3ye+9iFvK6sKUa6dgfMAZBUw7T205aBZwXiOdqsT+2swdeJkEWiwjjcIEiMFvKOgjb6zEWMnOUoC0IVezbPtvjJjrGo3gSoiEofXlTmrktihXc+K4n6cox07czNbMTAartiYB22yImFQGWHJYxl7hVAbyQ6oSEUWK+9gV+mIFTCD71Y5khzlsbp/UtHSxoBwUDS7kzW+k2IYi6ipLH2KYv1ENWk/pMVYCYWt77CN/j6XQabavONehBgHAok+Tq5/yon8np/ZO66LzFx+VFFyNxDvA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
