# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wYhbh5TW0Rinux4DwnoKincBZ6daWLb9GAZ8SLXGrgD8D7KoGzbDZOEAUEuLgZacWhMnNSYU8y2RYS3bvpneWuDz8pT7QwdQ2wUD7ps76uvcxOqpOoeCb/KWre5dVzwh7zp8EsZvHWP+97Fz6iepy+Hu7SMHj7xk7K5/WcuEzo8HTHD6P/ovRa5b8mooxKx968Ze4HYb+qZpnmsQMD4penRcdrqo/so/OfMXp9zGs9HGQF9/7GRBaBBAPUxJ3gARdk/fhiW8i/7xIZinXuM5+zPCUXrjMHw8jI22ter4VN3JDL2LzoFOtom97ANKkp7Udh8270IAP4VLXt8MkeeSTvmvLj7QivQlwEXyHSCVoC5OiGn1gfYj+V86drGVhx2eOMBMQw57xN3YMXw0/4tFKjyju/902qKF+0pQkENazcUwiTmBVZC9JOZjjtIkrJEqnGCEwhfPNs6G/AepuKX2p4EyauuCsckVRuo7K/gx6ytFgv+CZE5gpiHTfHE/vKMLcOhXe5m+LbZDrqnSqwJIjMpTXeMVvDzqrSu6Ii3cWLeFgVMPyukBjCP9atJ/+5ucIm/gUIJt3mONPkflMfhKQbmtm+nvkj3OzXyPo5kC7MkSXXEEXU1xZy2uvh2+fAQNF9UCVqOb0kdfxI+zCvxq/ohNKAYc2H+qUka153eiZPU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
