travis:
  secure:
    BINSTAR_TOKEN: wYhbh5TW0Rinux4DwnoKincBZ6daWLb9GAZ8SLXGrgD8D7KoGzbDZOEAUEuLgZacWhMnNSYU8y2RYS3bvpneWuDz8pT7QwdQ2wUD7ps76uvcxOqpOoeCb/KWre5dVzwh7zp8EsZvHWP+97Fz6iepy+Hu7SMHj7xk7K5/WcuEzo8HTHD6P/ovRa5b8mooxKx968Ze4HYb+qZpnmsQMD4penRcdrqo/so/OfMXp9zGs9HGQF9/7GRBaBBAPUxJ3gARdk/fhiW8i/7xIZinXuM5+zPCUXrjMHw8jI22ter4VN3JDL2LzoFOtom97ANKkp7Udh8270IAP4VLXt8MkeeSTvmvLj7QivQlwEXyHSCVoC5OiGn1gfYj+V86drGVhx2eOMBMQw57xN3YMXw0/4tFKjyju/902qKF+0pQkENazcUwiTmBVZC9JOZjjtIkrJEqnGCEwhfPNs6G/AepuKX2p4EyauuCsckVRuo7K/gx6ytFgv+CZE5gpiHTfHE/vKMLcOhXe5m+LbZDrqnSqwJIjMpTXeMVvDzqrSu6Ii3cWLeFgVMPyukBjCP9atJ/+5ucIm/gUIJt3mONPkflMfhKQbmtm+nvkj3OzXyPo5kC7MkSXXEEXU1xZy2uvh2+fAQNF9UCVqOb0kdfxI+zCvxq/ohNKAYc2H+qUka153eiZPU=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
