travis:
  secure:
    BINSTAR_TOKEN: ZbPfMJeD7fXge5IXsUlCzqocl2sI7FDVNmgQ5qIo7HasS9g6QzkVcU8NclW1o2S/7WPXdwJttatwUI+5EYkUlE7r25nZwclJkf4VhnYtUJhxDQhH1DLNBgwsU3Twmh1cZ2KGAxx9j1xLDKbDQYEHVSytDBRtXpZGUBYEJEWgvl9V+EEEsx2KRMjEBAYm1lU0CDY4JX7MUJhnZ0RQS37irFuHHa077WmaXSPWtV8lPiF9+zkt6MI8Ycd61F5kUo1jM9S8MX0nSUuFfyrFljsWPUNXutlOVu+K4u2Dun72Zd9yXQyrl7sYWjihVI/qDjmgiyPWS/7VLV6E9z4r6D4B05wq+5Mvzvf20YCPt07u+xSd3hDGIeWRkhSowVsK3si73DVFfh3TX2VQN4RJmulzetYugCGtgwt8Rv5WYlLfsjw8Ivbf4drnrVPYOGx0ZyquKaEkki44VXgyDBNf4g/4DiMtRp0crTQw41MwPUYb7Tx9qXVLps23kocm2jhv45UYT9fXeTHCFZnXlpJGRMUiSXj9G1HNDtKoBK8z9DpQ2c3aOjebDbnBmFYFgowZaBaiXBZgT+c1NlOqjkMHOzcJVWg4/gBXq7WEg6LT9kpqogUmAZ8dprmquXeulsffJcdylONpYq7ZDwu69EBLaPC6E16EoW1n0rh8hEhZEZbkMXg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
