travis:
  secure:
    BINSTAR_TOKEN: F+XHu2+N49O4cjX4Lzd5JwAnwez/EYUk6sOLQipiQ2tYLBANqnm3yCXQ+ocldpGF6sTk/jx1wca0QEBsp+97Cq0UyhySYPEXLHNjmShjKS0aiq4a+WBldB63vWQVdvitn4AwvQrByX2FKQm59KtAG5Vd00zE+eq3v65jf3NfSNgdw25jY3EGV75whAzFlgoRBJwIGmaOsIJ23uJazIt6oVRd2KEsIStuoNwhYr1JFxJ4ciQ1BieMGkAfFctDP/k5ckbeKTUBIkELRJyEce4bWfOgcsMkY4ZUe6m/X61vlav3aPYB5bzC60+4+hM6ugf4gicrw8ri9cJZ3igv+s6b5yEa9xXzurELVn2MkpcVEgqGJYbZ9A8dh6sOjHrGCL+lQ/8MZBX4rFgx9EQWMt3KAPKXlf8Z6BoDLCw7FuH1vRBAKFUdJzf9r75eh9tuy0864CopMe82j7jg5X8stx3rLjz3ea7k2N7xYcFySx9aZRitDHcPSLJh454OxRgoWi97FY0RQyg5EqfKoO293xSkvFqPFcjFvdXTCmO6gglbsPjuBSQp8ctUzQkLIW1DkKSCX2Kv+w67rqQ2yWwnajltaYug8E0Lig4JBp3cqR2yi7+Bau8wrhTEAOHpIkAg7q3dK5NyQzrz7r6ZbntyyWWAQYFyDRt0o356IvcaclxrLuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
