#{% set commit="master" %}
#{% set commit = "jjh_aarch64" %}
{% set commit = "5888cf1967ead937f0f2132fd24c55b9a8be6309" %}

package:
  name: crosstool-ng
  version: {{ (GIT_DESCRIBE_TAG or "").split("-")[-1] }}.{{ GIT_BUILD_STR }}

source:
  git_url: https://github.com/jjhelmus/crosstool-ng.git
  #git_url: https://github.com/continuumio/crosstool-ng.git
  git_tag: {{ commit }}

build:
  number: 5
  missing_dso_whitelist:
    - '*'

requirements:
  build:
  #  # TODO :: We need some [not bootstrapping] selector or something?
   #- {{ compiler('c') }}
   #- autoconf
   #- automake
   #- bison
   #- flex
   #- git
  host:
   #- ncurses
   #- libtool
    # There are two packages called 'wget' on defaults, one, the real wget and the other
    # a pythonic implementation from Anatoly Techtonik. At present, conda is installing
    # the latter unless I force the version(trying without this now, I believe Ilan may
    # have removed Anatoly's?
    #- wget
  run:
   #- ncurses
   #- libtool

test:
  commands:
    - ct-ng -h

about:
  home: http://crosstool-ng.org/

extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
