travis:
  secure:
    BINSTAR_TOKEN: jb6zNN2i4iHurXuA+o/RrFtlBPSfInLgj1oorKQNa5hmFxknZf2912mrR0Ai1bxQGNJl86tPzFfPKeVspupvCcMNcOpXU+DA1EjsyZHbZNBqqoZmRji8wKePYH4SAw+rFSCYnpTnCAC77Ng6wqJoWiOqJ5JlMKAJVlruC2ydKnRYS+SVVl/7B+NUdeB96qxDlrLK+ZBRF5ewkFoEV4BWXjo+CZuTkKho/Ze/iNcNbiy+xM0E9d2apO0iecV2IpYhTcn1D9oSqwPjG3XenSZWqdkbHjJuQlFo3GH3nlmIqdqdp3Eo8fP3ZLYlWuydwW+abcpE9vGppr5RR9aNiYdBFM0USvZySY3I6tj7iojZm51fzWi85WLNwL6iTpyfssmzn2KLFmH8LVmsOgu/0gWo8gWzy3eB2aLfxTw7jTY6FW4VKSQregN7Bp+BS47MFovow/5WODzCbZEr+iqwWdwZTv9LB6ruxxjDgm1QnY+MReoxEOeGdcLxdkQco8SvMIfg0Ci0RlGn35pN17cgFOlT9wR7Mhs4TsSJMvJcJyT+lpN6QbSguaWjK/NYNEYqcDscaKjM8MhmzPNV3sCf8mN9CkB/Twy4vlbDhBOtOQnHT2fX+Zsmq5tqZHL6kcUpQHm6fWDooZP0QmOfS3otriKmxIe9rir9AVwFQeJJ0pb3yOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
