travis:
  secure:
    BINSTAR_TOKEN: WcZbqxIWbJHbFStETNrZGMaORa4PbWHhxMMCeHlsdpRLF81QUOWOzdT1Z0Eq/fkG5dWDYtwNxFCcWwzmdXwXst2nsmfYUQ/sbVxpBUT3AAxfTalNt9LZb49G5Iajxplxme/dPW+r859VcmJkrLGbxLWQr/UhBC37ORfrhe/hJHtYfwo2vdN/JbsvgmlDplB7KIebv0mRvZwHkCtmZ8zp+fwhb9MxJqMbHxyGDYtvBYPHBcFSnkE5ZnvtQ5wx7NF8qUxO1uRDNDWOnCm/PwXFol0HkkyaLca2vb2SdUbfkbs42jCFli0hqMFWJnEscvN49kn3dGaOhMfzgtLyJBaDLS63IsgWyoH62X8oefGpYOyLTzeqph9Nb51Fm1PcmSGuDgi2TLkzZX0ukoxEJV/02av1krfp63nGwB+8XI1uvQVoC4ygxNa4PNdxYfSxGCgTve3Lx4e3L5noEugVdi6anRKPi504eGiAeORDoSGDzVAkubm0pdNKX71t1uNVhjAltZ94l+TRIFjLLHNk1z7CX1WSrI55Y4toFc+KXkNFJGhZ0MU9mHZJ61wS9T45LQtxPiRKySLB+vFDgSPmebY00lUtVzHUraa8xdNEEbeQ5kXf31HjxX3+JKMu+e/RBc9evrGQzotL8hjl+hsod1xANpfeVtCaLnwQFYiXxlh7Ns0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
