# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BYosKNNWII4U7qdLO5ZPQA2tQbkFq605R0y5memcpiuorqFYM17GRkta/qE4mGL/HtuXDFstLy6H/3wkxCUlNC/in+j/OPIia2ytmbPDxANSzfMZSbhM+3vmMhs37qLcVtBxV3WAzYRYN0uPrlDEByA3N6KjFTcHKSHi7V2zS60hOjNiAI36Iwx1wpRrxViImKDS+d4SmMirpOcpj0IojGbTh1QtLV9Xmr81q3vK8LmYxbReaComTjI1k3tULxEFWh4bflYJr2H9oQ6baHqT+Bt2L36mlmSO+LCJyoFtGmb1FdudRiEYd+uIhA78psmXJMar6kVaVBwdCGEeljIczcIkqULGi8CA8PV/rvfYk4EFjSCutx8DPf96acKJjfsh73APDDtUqj0kTmfbcmV1hgJIHurjxTEBjSFR2lNMRrST6pfkUq7zjsksfJy9Is+4PNtg9GshqKFAfEH8ca/dSzAfuPfVs/FexWVlnXY/K7msF0mJBVggL/HwwezIFZBkgBoujdwGPMyKih+tT43KaPGPUEGyIbxdwGkv7cjo1q1iXM5XSSlnV+mEouS7Hic+5lLY/MxPwIXo5daeH9kOfzxMej5X8FuIWZTYyV2AovKGA+vI+hlxnMCO+xgsNlpFnx1B/+BHWXrPNKpqF1o9ZeFAo3w70GkvMRZYYaGcL38="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
