travis:
  secure:
    BINSTAR_TOKEN: BYosKNNWII4U7qdLO5ZPQA2tQbkFq605R0y5memcpiuorqFYM17GRkta/qE4mGL/HtuXDFstLy6H/3wkxCUlNC/in+j/OPIia2ytmbPDxANSzfMZSbhM+3vmMhs37qLcVtBxV3WAzYRYN0uPrlDEByA3N6KjFTcHKSHi7V2zS60hOjNiAI36Iwx1wpRrxViImKDS+d4SmMirpOcpj0IojGbTh1QtLV9Xmr81q3vK8LmYxbReaComTjI1k3tULxEFWh4bflYJr2H9oQ6baHqT+Bt2L36mlmSO+LCJyoFtGmb1FdudRiEYd+uIhA78psmXJMar6kVaVBwdCGEeljIczcIkqULGi8CA8PV/rvfYk4EFjSCutx8DPf96acKJjfsh73APDDtUqj0kTmfbcmV1hgJIHurjxTEBjSFR2lNMRrST6pfkUq7zjsksfJy9Is+4PNtg9GshqKFAfEH8ca/dSzAfuPfVs/FexWVlnXY/K7msF0mJBVggL/HwwezIFZBkgBoujdwGPMyKih+tT43KaPGPUEGyIbxdwGkv7cjo1q1iXM5XSSlnV+mEouS7Hic+5lLY/MxPwIXo5daeH9kOfzxMej5X8FuIWZTYyV2AovKGA+vI+hlxnMCO+xgsNlpFnx1B/+BHWXrPNKpqF1o9ZeFAo3w70GkvMRZYYaGcL38=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
